### ISSUE TITLE
Article images max-height forced to 64vh

### ISSUE THREAD

**Issue by victorvalle** [liferay-design/liferay.design#488]
This line is working against us in some articles.
Why do we have a max-height?

**Comment by plhnk** [comment]
This was a fast solution intended to prevent images from taking up too much of the screen: 

(without max-height)
<img width="1552" alt="Screen Shot 2019-07-31 at 10 40 14 AM" src="https://user-images.githubusercontent.com/10226086/62234514-b0cdb300-b37f-11e9-8db7-1294d70ec005.png">
<img width="1552" alt="Screen Shot 2019-07-31 at 10 39 06 AM" src="https://user-images.githubusercontent.com/10226086/62234515-b0cdb300-b37f-11e9-8f9e-d0a235570d39.png">

(with max-height)
<img width="1552" alt="Screen Shot 2019-07-31 at 10 40 12 AM" src="https://user-images.githubusercontent.com/10226086/62234653-f68a7b80-b37f-11e9-837e-7c72f7e4581f.png">
<img width="1552" alt="Screen Shot 2019-07-31 at 10 39 09 AM" src="https://user-images.githubusercontent.com/10226086/62234654-f68a7b80-b37f-11e9-9744-89859f1ba861.png">

Open to suggestions! Note that this is implemented in 4 places (also a fast solution) so ideally the fix is applied to all four places...even better, set up a single place for this fix! :D Thanks sir

**Comment by plhnk** [comment]
(#322 is potentially related to this...)

**Comment by plhnk** [comment]
@victorvalle did you have more thoughts? specific places where this is negatively affecting images? I'm inclined to close as it's over a year old :)

**Comment by plhnk** [comment]
🔔 🔔 🔔  @victorvalle 🔔 🔔 🔔 

Do you want to keep this open? A lot of things have changed in images, I'm not sure if this is necessary — please take a look and add any more clarification if we should move forward.

**Comment by victorvalle** [comment]
no... It happened a long time ago. No need to keep this open.
