### ISSUE TITLE
Reorder Handbook Menu

### ISSUE THREAD

**Issue by fapires** [liferay-design/liferay.design#734]
With the addition of Lexicon to Handbook, Lexicon option wen to the top of the menu list:
<img width="308" alt="Screen Shot 2020-05-14 at 10 57 06" src="https://user-images.githubusercontent.com/8724228/81943908-5cc05200-95d2-11ea-8635-1468ef3f2c70.png">

Taking into consideration the IA, I don't think it should at the top of the menu. My suggestion would be something like this:

1. Principles
2. **Lexicon**
3. Work
4. Tools
5. Collaborate
6. Advocate
7. Grow
8. Contribute
9. Resources

**Comment by victorvalle** [comment]
In my local repo I see it properly ordered
![image](https://user-images.githubusercontent.com/21121115/81952494-d8d48d00-9606-11ea-89cf-007c83a70b1f.png)

**Comment by victorvalle** [comment]
Could you clean you cache(cmd+shift+R) and try again @fapires ?

**Comment by plhnk** [comment]
the sidebar order is determined by the `order` field in the frontmatter:
![image](https://user-images.githubusercontent.com/10226086/81957050-eebf5f00-95c0-11ea-9dcb-f6df07f74e54.png)

Both Lexicon and Principles have `10` set - in case of a conflict, it's a coin flip at build time which one will be first — in our case, when the site was built in Netlify, Lexicon is on top, in @victorvalle's case, when it was built on his local machine, Principles is on top.

To solve this —> change the `order` property. I realize this is not ideal, as its difficult to know the order of all of them in relation when its set in separate files...but on the other side, if you have a lot of pages then it can be annoying to manage the navigation order in a separate file.

## All that to say

1. Does it make sense to have Lexicon at the top-level? 
1. Would it make more sense in `Tools`? 
1. It's already linked in `Resources` — would it make more sense to have it there?

Keep in mind, we do have Lexicon as the first card right below the fold...thoughts?

**Comment by fapires** [comment]
Thanks @plhnk! Just sent a PR to update that.

1. I think so once it's our primary resource for designing products.
2. It's more than a tool, because of that I think it needs more prominent on the AI

**Comment by plhnk** [comment]
Thanks for sharing @fapires, I think there's an important distinction to make — just because something is important (I'm not questioning Lexicon's importance or significant) — does not mean it is relevant to all contexts.

Due to its importance and evergreen significance, Lexicon is included in a few different places (as [mentioned previously](https://github.com/liferay-design/liferay.design/issues/734#issuecomment-628733419)). However, in the specific context of the sidebar, which reflects the overall IA of the handbook, it seem inconsistent to surface it at the highest level.

@drakonux if you have moment to weigh in? You are more of an expert on IA than I am, and you are closer to the project so will have more things to share.

**Comment by drakonux** [comment]
Hot potato.

Well, the first thing working on IA is the intent. So what's the intent of the Handbook? That answer is very important to orientate the direction of the taxonomy. 

A classic example in IA: the right section for tomatoes in the supermarket. They are placed in the vegetable section but they are not vegetables. Because formally they are fruits. But the way how people consume them has changed the classification they have in a certain context. 

The second thing, the taxonomy of a menu could be or not related to the actual structure of the site. Good taxonomies detect items buried in a hierarchy and make interventions to stand up it. 

The third thing, taxonomies need to be iterated. Test it, gather the data, propose changes based on the data, and repeat to see the new results.

Said this, I'm going to say some assumptions about Handbook:

- It is the information **reference** for all the designers in the company (any type)
- It declares:
    - our principles
    - how we work
    - how we would like to grow
    - how we collaborate

About Lexicon:

- It's Liferay's design language. 
- It's probably the most valuable information resource for product designers.
- Although, we are waiting for the [research data](https://issues.liferay.com/browse/DESRES-37). It's probably the most visited resource in liferay.design. 
- It should gather knowledge of every product and every designer in the company.
- Currently, it's only oriented to products but IMHO we have to evolve it in more directions (branding, etc.) and take advantage of the naming.

So talking about the taxonomy in the menu, even if Lexicon is formally a tool or not. I think the department's intention should be to reinforce the impact it has on liferay.design and the Handbook. It was buried on the home page of liferay.design not a long time ago... and even now, it's complicated to reach it.

**Summarizing**
It's up to you. The people who lead the design of the company to reinforce or not a settled concept. 
If a relevant place in the taxonomy is too much, I suggest trying using the Lexicon logo in the basement with a link to Lexicon Site.

**Comment by plhnk** [comment]
So — you support putting it outside of the taxonomy, in the top level of the sidebar? For me, it's ok — just want to have another voice besides me and @fapires :)

**Comment by drakonux** [comment]
I agree to have it as a first level of the hierarchy, yes :)  

Placed first? maybe it is too much, so probably a place between "Contributes" and "Resources" section is a good place (test it). But IMO I don't see "Contributes" as a section [I am a pain in the neck sorry] for me all that content should be in a page reachable with a link that can be on the footer of each Handbook page.
