### ISSUE TITLE
Jon Wood's team icon is not appearing white

### ISSUE THREAD

**Issue by ryconn888** [liferay-design/liferay.design#766]
1. Go to liferay.design/team
2. Look at Jon's icon
3. Notice that it's not the same color as the others

<img width="1657" alt="Screen Shot 2020-08-11 at 1 57 09 PM" src="https://user-images.githubusercontent.com/27976451/89948218-92c5a000-dbda-11ea-84b9-f749ad26d8f1.png">

**Comment by victorvalle** [comment]
Just changing the icon fill property from currentColor to white in icons.js, it works. But I'm not sure if this is what we want.
Another solution could be adding the color property to Icon class and stating the color in each case. Probably @plhnk  has a better solution for this issue.

**Comment by plhnk** [comment]
I like how @victorvalle responds to gh issues, but not my whatsapp messages 💔

**Comment by plhnk** [comment]
but he's right — changing the fill property in the icon itself will fix it, but he's also right in that it's not a scalable solution as it hardcodes a value (`white`) in something we might want to change.

It looks like if we move the `fill` property up a level (to the `svg` instead of at the `path`) this would solve it — and also maintain the future flexibility.

I suggest we take this ticket and do the following things:

1. Make this fix across the board for all icons (set `fill="currentColor"`) — note we'll need to adjust should icons use the `stroke` property instead
1. Add this requirement to the icon documentation
1. Test all places where <Icon> is used to make sure no colors are broken

**Comment by plhnk** [comment]
fixed in #768
